<?php
/**
 * Theme bootstrap file
 *
 * Please do not edit this file in any circumstances.
 *
 * @package     Zoo Theme
 * @version     1.0.0
 * @author      Zootemplate
 * @link        http://www.zootemplate.com
 * @copyright   Copyright (c) 2017 Zootemplate
 * @license     GPL v2
 */

/**
 * Theme version
 *
 * @var    string
 */
define('ZOO_THEME_VERSION', '1.0.0');

/**
 * Theme base path
 *
 * @var    string
 */
define( 'ZOO_THEME_DIR', get_template_directory() . '/' );

/**
 * Theme base uri
 *
 * @see    https://google.github.io/styleguide/htmlcssguide.xml?showone=Protocol#Protocol
 *
 * @var    string
 */
define( 'ZOO_THEME_URI', preg_replace( '/^http(s)?:/', '', get_template_directory_uri() ) . '/' );

/**
 * Load theme functions and definitions
 *
 * @var    resource
 */
require ZOO_THEME_DIR . 'inc/init.php';

/**
 * Load theme core functions and definitions
 *
 * @var    resource
 */
require ZOO_THEME_DIR . 'lib/core.php';
